version: "3.8"
services:
  webapp:
    build: .
    ports:
      - "5050:8888"
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: monolith
    volumes:
      - ./base.sql:/docker-entrypoint-initdb.d/base.sql
